///|
typealias @syntax.(
  IDLType,
  StringType,
  IDLTypeWithExtAttr,
  IntegerType,
  FloatingType,
  ExtAttrs,
  ExtAttr,
  Typedef,
  Enum,
  Includes,
  Dictionary,
  DictionaryField,
  Callback,
  Rhs,
  Attribute,
  AttributeKind,
  Member,
  Const,
  Operation,
  OperationKind,
  Namespace,
  Interface,
  InterfaceMixin,
  SetLike,
  MapLike,
  Iterable,
  Argument,
  Definition,
  Constructor,
  Value,
  Id
)

///|
typealias @list.List
